{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","msg","name","exception","isApplicationException","err","Object","getPrototypeOf","getExceptionMessage","message","console","log"],"mappings":";;;;;;AAAO,kBAAMA,oBAAN,SAAmCC,KAAnC,CAAwC;AAC3CC,4BAAYC,MAAM,EAAlB,EAAqB;AACjB,0BAAMA,GAAN;AACA,yBAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACH;AAJ0C;;AAO/C;;;;AACA,kBAAMC,YAAYL,oBAAlB;;AAEO,qBAASM,sBAAT,CAAgCC,GAAhC,EAAoC;AACvC,uBAAOA,eAAeF,SAAf,IACHG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SAD1C;AAEA;AACA;AACH;;;;AAEM,qBAASK,mBAAT,CAA6BH,GAA7B,EAAiC;AACpC,oBAAID,uBAAuBC,GAAvB,CAAJ,EAAgC;AAC5B,2BAAOA,IAAII,OAAX;AACH,iBAFD,MAEO;AACHC,4BAAQC,GAAR,CAAYN,GAAZ;AACA,2BAAO,uCAAP;AACH;AACJ","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error{\r\n    constructor(msg = ''){\r\n        super(msg)\r\n        this.name = this.constructor.name\r\n    }\r\n}\r\n\r\n//hack do system.js para que a função tenha acesso a definição da classe\r\nconst exception = ApplicationException\r\n\r\nexport function isApplicationException(err){\r\n    return err instanceof exception ||\r\n        Object.getPrototypeOf(err) instanceof exception\r\n    //verifica se o tipo ou o prototype da exceção são instâncias de ApplicationException\r\n    //o teste do prototype é importante, pois sem ele DataInvalidaException retorna false\r\n}\r\n\r\nexport function getExceptionMessage(err){\r\n    if (isApplicationException(err)){\r\n        return err.message\r\n    } else {\r\n        console.log(err)\r\n        return 'Não foi possível realizar a operação!'\r\n    }\r\n}"]}